### ISSUE TITLE
Bitbucket support

### ISSUE THREAD

**Issue by vhugogarcia** [msusur/git-mish#2]
Hello friend,

This is a pretty cool library. Thanks for sharing.

However I'm having issues trying to make it work with a bitbucket repository, is there a sample you can share, about to to perform a pull on a bitbucket repository (Git) https://bitbucket.org ?

Thanks in advance

**Comment by msusur** [comment]
Hey there @vhugogarcia ,

Frankly, I didn't test it for bitbucket. Can you please explain what do you want to achieve? I will try my best afterwards :)

**Comment by vhugogarcia** [comment]
Thanks for your answer.

Basically what I want to make is this: https://confluence.atlassian.com/display/BITBUCKET/POST+hook+management

In summary, when I perform a commit->push in my local computer, I want to fire a POST hook in bitbucket that will load a website page, and on this website page I would like to perform the git pull of the repository, so the server grab the latest version from Git automatically.

This will help me a lot on development.

I have an account in Bitbucket and I can share a test repository, so you can join and take a look, if you want.

Thank you so much for your help, really appreciate it.
